apiVersion: v1
kind: Service
metadata:
  labels:
    app: flachwitz-api
  name: flachwitz-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: flachwitz-api
  type: NodePort

